language: node_js
node_js:
  - 10
deploy:
  provider: npm
  email: erik.gustav.dalen@gmail.com
  api_key:
    secure: GM+FZd4ig949SQQTKMu9Ogm+RGVi8a3IUu+hmsoUCKVTSertxCNzIucb32xKRcnR/QxMVlSTb+02D9sVpUMvCrfOuGSFAb049ZvCBMCndyll7B2nDS6VkqZaGkiajcv1M8/1pkPXv6gkQO/8dCPFk2a+oUEXjk9RZOGwiNDwYNAhOlqiw7VKBI6QczYz0c6HFNwFYwsK/HY0YFctEpRsd2iKLzM1YmZb29OFU/KiqxGgPK1TEF88gaaYoMQTR+AIAvH8fhLNUl+9H4MYXrwl2n7k9MA4WKsB9QUF1f5mqhMUGUoNPrLsVv+hS7uc98U658UOrmTeTw2ed+bp109g4a1F45Y0+A/VRl8pOf0Z4nzEg5rYMevs76Oxmn+9YYZ2VTWMXxEeziWF8IVC8R69ene8havDE9ikHLFM6JZRZTp/dPpd8ByLkj0BstHyVVJaXoiKLYto49EQtkrUFWvV53Fg0WZNLoZ6R4d9B1V9hbLgPa7NPgdLyX/hAMK+4sv396x54aq2IP/S+GO3D92mMHwlVmy7Hpnm6QTt6aJJA6WGRtDcrIIthdy1INrgewo3szdkPXg61IhiIxHaIMm3ypcU1DeDixuXogIOD3qvW/n4AnULkjvQvVhbCplpBf59Bf5udzhOl/k3iK5BaI/ETi/qLrXnwrG5JZHDKK1y2k0=
  on:
    tags: true
